<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select options</name>
   <tag></tag>
   <elementGuidId>2c6cfb22-6446-48cf-a1ca-bfc45a575e3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.noo-product-item.one.noo-product-sm-4.not_featured.post-1441.product.type-product.status-publish.has-post-thumbnail.product_cat-bodycon-dresses.product_tag-bodycon-dresses.product_tag-women.has-featured.last.instock.shipping-taxable.purchasable.product-type-variable > div.noo-product-inner > div.noo-loop-cart > a.button.product_type_variable.add_to_cart_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='noo-site']/div[2]/div[2]/div/div/div[4]/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c6eb679-7502-43c5-8aee-948d55ace503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://shop.demoqa.com/product/black-ribbed-short-sleeve-lettuce-hem-midi-dress/</value>
      <webElementGuid>bc1fd01c-22d4-42c9-9ece-9d338fe05090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quantity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>46df56e3-af0c-4d78-9381-9d4e44e5cde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button product_type_variable add_to_cart_button</value>
      <webElementGuid>3f915b37-5178-412f-a85d-2f9e9e5f12e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>1441</value>
      <webElementGuid>7dd2c857-b883-48c4-84d2-1655aceb0e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select options for “black ribbed short sleeve lettuce hem midi dress”</value>
      <webElementGuid>90d5efed-6fe0-4c69-8f29-643886e018ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>aeab9d1f-f645-43ec-985e-605cc8abebd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select options</value>
      <webElementGuid>30e01d97-ffba-4ace-a385-d2a263f1c8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noo-site&quot;)/div[@class=&quot;noo-container-shop noo-shop-wrap&quot;]/div[@class=&quot;noo-row&quot;]/div[@class=&quot;noo-md-12 one&quot;]/div[@class=&quot;products noo-row&quot;]/div[@class=&quot;noo-product-item one noo-product-sm-4 not_featured post-1441 product type-product status-publish has-post-thumbnail product_cat-bodycon-dresses product_tag-bodycon-dresses product_tag-women has-featured last instock shipping-taxable purchasable product-type-variable&quot;]/div[@class=&quot;noo-product-inner&quot;]/div[@class=&quot;noo-loop-cart&quot;]/a[@class=&quot;button product_type_variable add_to_cart_button&quot;]</value>
      <webElementGuid>a7ceb8d4-8361-4749-a3f7-b24a74751887</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noo-site']/div[2]/div[2]/div/div/div[4]/div/div[3]/a</value>
      <webElementGuid>6ad7f59d-ce75-4be7-ad0d-b26a660543a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select options')])[4]</value>
      <webElementGuid>7995e8bb-cc4a-4ea7-b688-9c4df25d0856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[5]/following::a[1]</value>
      <webElementGuid>0af841d8-7594-421f-ab91-73f8569924ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='white new season belted bodycon mini dress'])[1]/preceding::a[1]</value>
      <webElementGuid>1bd072c1-0f74-4835-a316-e7376d194d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dress'])[1]/preceding::a[2]</value>
      <webElementGuid>aa23ec55-3de9-49d7-a57e-b1313b5605fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://shop.demoqa.com/product/black-ribbed-short-sleeve-lettuce-hem-midi-dress/')])[6]</value>
      <webElementGuid>5fc1cbae-f49f-472d-9a72-5884237d76cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/a</value>
      <webElementGuid>1d1eafce-ca30-46f6-af71-4ca11ebfeed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://shop.demoqa.com/product/black-ribbed-short-sleeve-lettuce-hem-midi-dress/' and (text() = 'Select options' or . = 'Select options')]</value>
      <webElementGuid>c3a3feb7-421f-47cb-9b35-9237991fcf94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
