<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billing_postcode</name>
   <tag></tag>
   <elementGuidId>dac15f7a-f631-4403-bc11-2ec94247779f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_postcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_postcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6f2f97e-a11a-4b57-9380-747696092b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>558db3ff-b4a1-40b0-b8a7-11824106cb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>aef40c0f-ff92-4313-8395-c3ac3d7f8ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_postcode</value>
      <webElementGuid>1cfb666a-3e10-4a94-b189-561ecabb4971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_postcode</value>
      <webElementGuid>300e07e0-0a05-41c4-9ed1-cdec659874b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>postal-code</value>
      <webElementGuid>54f735b3-ab16-4d0d-af8b-9d8cdd43b68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_postcode&quot;)</value>
      <webElementGuid>187da6df-9f4f-4867-b303-e96ae2c00911</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_postcode']</value>
      <webElementGuid>30dcfed3-cc24-4f0a-bc6f-1cbb61824046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_postcode_field']/span/input</value>
      <webElementGuid>b9935d0f-45fb-4a27-b911-3d499f6861aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[9]/span/input</value>
      <webElementGuid>7b305d05-188e-4fc4-a49d-7616f6314bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_postcode' and @id = 'billing_postcode']</value>
      <webElementGuid>90feb215-7122-472f-ae44-b7cb9a9dd46b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
