<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__createaccount</name>
   <tag></tag>
   <elementGuidId>d71ea423-6f32-46b6-a9fe-c097311d8470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#createaccount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='createaccount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7b98894-22f6-416f-9fb9-23c1fcb10570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-form__input woocommerce-form__input-checkbox input-checkbox</value>
      <webElementGuid>3eeab5b4-7c91-4b05-a85a-948c477b99b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createaccount</value>
      <webElementGuid>588d3b9d-5c4b-4a50-b4b6-2901371d60a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>505a6bf0-fd19-4176-a22b-b2e35a104010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>createaccount</value>
      <webElementGuid>179a5fa4-4f93-4682-93d7-ff68822c2126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3f6d4f33-b495-4ff3-9b87-b979bbf430e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createaccount&quot;)</value>
      <webElementGuid>7dafc5b5-cb21-4310-90d3-cd40ec5576c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='createaccount']</value>
      <webElementGuid>8006bc74-0231-4614-bb5e-eb552a09d84d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_details']/div[2]/p/label/input</value>
      <webElementGuid>363b3bd0-258d-4058-ad76-9a4afbdca546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p/label/input</value>
      <webElementGuid>da037fab-a0ef-4b52-a1d5-321dd91fd2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'createaccount' and @type = 'checkbox' and @name = 'createaccount']</value>
      <webElementGuid>67863481-c1b5-4a1b-855e-071ac5939650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
